//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida_Jugador
    {
        public int id_partida_jugador { get; set; }
        public int id_partida { get; set; }
        public string nickname { get; set; }
    
        public virtual Partida Partida { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
